unimelb/unimelb-design-system

demo-site/views/example_layouts/floating-contrast.slim, templates/components/accordion/00-overview.md, templates/components/accordion/_base.scss, templates/components/accordion/accordion.coffee, templates/components/checklist/extra-label.coffee, templates/components/checklist/unlock-checklist.coffee, templates/components/filtered-listings/list-filter.coffee, templates/components/forms/validation.coffee, templates/components/inpage-navigation/inscroll.coffee, templates/components/inpage-navigation/jumpnav.coffee, templates/components/listings/_block.scss, templates/components/maps/gmaps.coffee, templates/components/media/yt.coffee, templates/components/modal/modal.coffee, templates/components/tables/tables.coffee, templates/components/tabs/sidebar-tabs.coffee, templates/components/tabs/tabs-inner.coffee, templates/uom.js
Also solve double loading issue and improve click zone, update example layouts
=> fix #158 update documentation

templates/components/base/_courses.scss, templates/components/base/_globals.scss, templates/components/tabs/_base.scss
Deleted all occurences of #0084ee to comply with accessible colour contrast
=> Changed $cyan to use $highlight as colour

pages/articles/audio-video-guidelines.slim.md, pages/articles/using-images.slim.md, pages/content-creators.slim.md, templates/components/headers/_article-header.scss, templates/components/listings/_nav_block.scss
added listing-style (block nav ul.narrow), added article header.noimg
=> Fixed content creator navigation, added styles

templates/components/filtered-listings/list-filter.coffee
=> Allow filtered listing to work without select

templates/components/base/_layout.scss, templates/components/notices/00-overview.md, templates/components/notices/01-examples.slim, templates/components/notices/02-links-in-alerts.slim, templates/components/notices/_base.scss, templates/components/notices/notices.scss, templates/uom.scss
added 'Notices' component with four variations @anormand can you please check the colour contrast is okay
=> Notices component

demo-site/views/example_layouts/course.slim, templates/components/inpage-navigation/jumpnav.coffee
Also: update sample layout to demonstrate
Resolves #267 
Resolves #255 (by accident)
=> Modify jumpnav to work within limits in tabs

templates/components/inpage-navigation/jumpnav.coffee, templates/components/timeline/_base.scss
=> Fix timeline

assets/targets/components/listings/_base.scss
Better placement on wide screen resolutions.
Close #286
=> Adjust widths and alignment of basic listings

assets/targets/components/base/_layout.scss, assets/targets/injection/nav/_localnav.scss, assets/targets/injection/nav/localnav.es6, doc-site/app/app.rb, doc-site/pages/audio-video-guidelines.slim.md, doc-site/views/articles.slim, doc-site/views/example_layouts/about.slim, doc-site/views/layout.slim, doc-site/views/nav_list.slim
Also
* Add base framework for article index
* Include example in doc site localnav
* Enforce namespace on layout
=> Slight modification to localnav to include planned meta listing

assets/targets/forms/index.js, assets/targets/forms/index.scss
* Add missing css to hide hidden block
* Add smoothscrolling handler on internal links
=> Quick fixes to forms target

assets/targets/injection/footer/index.es6
@waitingallday does this need to be changed in any other file?
=> Update facebook URL

assets/targets/components/gallery/01-default-gallery.slim, assets/targets/components/index.js
Also
* Update doc example to demonstrate multiple galleries
=> Rewrite with function outside loop as per jshint advice

assets/targets/components/headers/_headers.scss
=> Increase padding-top of header on mobile

assets/targets/components/base/_layout.scss, assets/targets/components/listings/_nav_block.scss, assets/targets/components/text/_lead.scss, doc-site/views/example_layouts/no-header.slim
Variant of lead text for header-less layouts.
=> Lead-left text and other minor staff-hub tweaks

assets/targets/components/tabs/index.js
=> Set href correctly for push state

assets/targets/components/inpage-navigation/index.js, assets/targets/components/tabs/index.js, doc-site/views/example_layouts/fake-tab.slim
Fixes #364 
Also, update example to reproduce enquiry bug and replace other `substr` calls with `charAt` for readability.
=> Tighten up tab hash checking, and inpage scroll interaction

assets/targets/components/tabs/index.js
=> Fix URL hash not updating when switching tabs

assets/targets/components/people/_people.scss
=> Fix detailed staff listing with long text

assets/targets/components/maps/lmaps.js
=> Update to our own defined tileset id and accesstoken

assets/targets/injection/announcement/index.es6, doc-site/views/example_layouts/intranet.slim
=> Dismiss announcement when following its link

assets/targets/components/enquiry/01-enquiry.slim, assets/targets/components/enquiry/02-enquiry-dark.slim, assets/targets/components/enquiry/_enquiry.scss
=> Dark version of enquiry component

assets/targets/components/enquiry/01-enquiry.slim, assets/targets/components/enquiry/02-enquiry-dark.slim, assets/targets/components/enquiry/_enquiry.scss, assets/targets/components/forms/_forms.scss, doc-site/views/example_layouts/fake-tab.slim, doc-site/views/example_layouts/intranet.slim
- remove strange top divider
- fix invisible sub-text
- remove/hide legend
Fixes #393
=> Tweak enquiry styles and markup

assets/targets/components/base/03-05-ordered-list-steps.slim, assets/targets/components/base/_typography.scss, assets/targets/components/text/01-body.slim
=> Add some common internal styles for step list

assets/targets/components/text/01-body.slim, assets/targets/components/text/_figures_floating.scss
=> Allow for jumpnav in floating figures

assets/targets/components/tabs/index.js
=> Add special condition for no-svg fallback

assets/targets/components/checklist/_checklist.scss, assets/targets/components/forms/_forms.scss
=> Fix checklist

assets/targets/components/base/_typography.scss
=> Fix steps list

assets/targets/components/base/_courses.scss, assets/targets/components/tables/_tables.scss, doc-site/views/example_layouts/course.slim
Also: always override for course structure layout
Fixes #418
=> Set overflow only on x and only below desktop width

assets/targets/components/forms/_forms-select.scss, assets/targets/components/inpage-navigation/jumpnav.js, assets/targets/injection/header/index.scss, doc-site/pages/audio-video-guidelines.slim.md, doc-site/pages/content-creators.slim.md, doc-site/pages/editorial-guidelines.slim.md, doc-site/pages/editorial-style-guide.slim.md, doc-site/views/page.slim
Fixes #277 
Try a new method, tested on windows ESR
=> Fix ff select

assets/targets/components/accordion/index.js, assets/targets/components/icons/index.js, assets/targets/components/index.js, assets/targets/components/inpage-navigation/index.js, assets/targets/components/inpage-navigation/jumpnav.js, assets/targets/components/modal/index.js, assets/targets/injection/nav/index.js
On accordion, icons, inpage-nav, jumpnav, modal
Also specify history behaviour on blanket binding (was adding to modals as well)
Also provide separate binding helper `UOMbind()`
=> Check for already bound events

assets/targets/components/events/_events-detail.scss, doc-site/views/example_layouts/event.slim, doc-site/views/layouts_index.slim
Including a whole new example layout
=> Adjustments for single page event detail

assets/targets/components/base/_layout.scss, assets/targets/components/buttons/01-overview.md, assets/targets/components/buttons/02-default-buttons-no-source.slim, assets/targets/components/inpage-navigation/00-overview.md, assets/targets/components/inpage-navigation/_jumpnav.scss, assets/targets/components/inpage-navigation/jumpnav.js, assets/targets/components/text/_code.scss
Also, documented the change and made a demonstration
Fixes #463
=> Added an optional top-only jumpnav

assets/shared/shims.js, assets/targets/components/base/_layout.scss, assets/targets/components/base/_titles.scss, assets/targets/components/inpage-navigation/jumpnav.js, assets/targets/components/text/_lead.scss, doc-site/pages/audio-video-guidelines.slim.md, doc-site/pages/content-creators.slim.md, doc-site/pages/editorial-style-guide.slim.md, doc-site/pages/getting-started.slim.md, doc-site/views/example_layouts/no-header.slim, doc-site/views/page.slim
=> Fix headerless layout

assets/targets/components/timeline/02-timeline-with-images.slim, assets/targets/components/timeline/03-timeline-as-figures.slim, assets/targets/components/timeline/04-simplified-timeline.slim, assets/targets/components/timeline/_timeline.scss
Review and merge for the next release?
=> Timeline with images

assets/targets/components/base/_layout.scss, assets/targets/components/search/_pagination.scss, assets/targets/components/search/_search-results.scss, doc-site/views/example_layouts/search.slim
Fixes #437 and was a combination of two issues:
- overflow of search result URLs
- `display: table` in `with-aside` layout on mobile
=> Fix search results overflow on mobile

assets/targets/injection/header/index.scss
Fix https://github.com/marcom-unimelb/Mercury/issues/777
=> Fix alignment of breadcrumb with icon

assets/targets/components/accordion/index.js
=> Allow section to be closed in single-block-open accordion

assets/targets/components/accordion/_accordion.scss
=> Fix accordion: clickable area + Chrome bug 

assets/targets/components/filtered-listings/index.js
* Update select to URL-fed section
* Add fault tolerance for unmatched URL filter (will now default to all sections)
=> Update filtered listing select to match URL

assets/targets/components/tables/_tables.scss
Was missing centre alignment and hugging the left on a wide table.
=> Center mobile wrapped table

assets/targets/components/forms/_forms.scss, assets/targets/injection/header/index.es6, assets/targets/injection/header/index.scss, assets/targets/injection/nav/_globalnav.scss, assets/targets/injection/nav/index.js
* Insert new search form markup
* Relink search button to new search, attach events to close and blanket
* Modify blanket style
=> New in-header search box

assets/targets/components/filtered-listings/index.js, assets/targets/components/filtered-listings/section.js, assets/targets/components/media/02-section-full-width-with-background-image.slim
Also update image src in example code.
=> Fix some minor regressions in classlist usage

assets/targets/components/inpage-navigation/_jumpnav.scss, assets/targets/components/notices/_flash.scss
=> Adjust jump-nav box-shadow to fix janky scroll in FF 45

assets/targets/injection/header/index.scss
=> Define z-index to highest level

assets/targets/injection/header/index.scss
Extend search bar to fullscreen to bypass opacity issue, style up buttons to be more readable
=> IE8 compatibility

assets/targets/injection/header/index.es6, assets/targets/injection/header/index.scss, assets/targets/injection/nav/index.es6
=> Fix search bar cross-browser issues

assets/targets/injection/header/index.es6, assets/targets/injection/header/index.scss, assets/targets/injection/nav/index.es6
=> Search bar animations

assets/targets/components/accordion/_accordion.scss
=> Fix numbering of ordered sublist inside accordion

assets/targets/components/filtered-listings/00-overview.md, assets/targets/components/filtered-listings/01-pre-select-filters.md, assets/targets/components/filtered-listings/_filters.scss, assets/targets/components/filtered-listings/index.js
Also, amend docs to recommend slugifying the names of sections and tags.
=> Filtered Listing: fix styles + fix case of pre-select parameters

assets/targets/components/inpage-navigation/00-overview.md, assets/targets/components/inpage-navigation/01-index-navigation-no-source.slim, assets/targets/components/inpage-navigation/02-smooth-scroll-no-source.slim, build/v4.1/components/inpage-navigation/index.html
=> Fix inpage nav docs

assets/targets/injection/header/index.scss
* Match background of search header to blanket (transparent white 95%)
* Hide header tools while search is active
* Add `position` and `z-index` while search is active to help with future layering
=> Improve search

assets/targets/components/forms/02-checkbox-and-radio-buttons.html, assets/targets/components/forms/index.js
=> Add radio type to presence validation

assets/targets/components/accordion/01-simple-accordion.slim, assets/targets/components/accordion/02-single-block-open.slim, assets/targets/components/base/_typography.scss
* Add ticked-list and no-li into inner reset mixing
* Expand documentation examples
* Eliminate tabs 🔥
Fix #648
=> Fix double display of bullet point inside accordion

assets/targets/components/forms/06-required-fields.md, assets/targets/components/forms/08-labels.md, assets/targets/components/forms/09-fieldsets.md, assets/targets/components/forms/_forms.scss, assets/targets/components/text/_code.scss
Also: 
* Fix rergression on inline inputs post- extend-removal (search field, subscription form etc.)
Fix #644
=> Fix documentation pages under forms component

assets/targets/components/events/04-single-date-event-page-with-presenters.slim, assets/targets/components/events/_events-detail.scss
… to single line to trigger ellipsis on hyphenated url
Also:
* Add example in documentation sample
Fix #640
=> Constrain link in aside panel

assets/targets/components/buttons/_buttons.scss, assets/targets/components/modal/03-inset-within-modal.slim, assets/targets/components/modal/_modal.scss, assets/targets/components/text/_figures_floating.scss, assets/targets/components/text/_two_columns.scss
Also:
* Add documentation example
* Fix regression in button-small font size & padding
Fix #643
=> Constrain inset within modal bounds

assets/targets/components/base/_courses.scss, assets/targets/components/filtered-listings/_filters.scss, assets/targets/components/headers/09-image-header-with-filters.slim, assets/targets/components/headers/14-course-header-short.slim, assets/targets/components/text/_two_columns.scss
Also:
* Fix a number of regressions in the header styles
Fix #635
=> Fix course header selector

assets/targets/prompt/index.es6, assets/targets/prompt/index.scss, assets/targets/prompt/prompt.es6, assets/targets/prompt/target.js, assets/targets/survey/index.es6, views/templates/survey-prompt.slim
Adds a new build target called `prompt`, and a demo template: `https://web.unimelb.edu.au/layouts/survey-prompt`.
=> Survey prompt

assets/targets/prompt/index.scss
Also, use rem mixin and fix ordering of declarations.
=> Fix prompt mobile styles

assets/server.js
Been meaning to deal with this for some time. Discovered the magic settings while working on Open Day....
=> Reduce console output of webpack dev server

assets/targets/components/text/_lead.scss, views/templates/staff-list-featured.slim
=> Fix regression in style

assets/targets/components/base/03-06-ordered-list-nested.slim, assets/targets/components/base/03-07-ordered-list-bracket.slim, assets/targets/components/base/_typography.scss
* Add the brackets style for legal documentation, contributed by @tomstringer 
* The nested list style was contained in a wrapper, but all others have been a class on an `ol` - easier to integrate with MCE as a class anyway.
=> Add brackets ol style, drop wrapper on nested ol style

assets/targets/components/accordion/02-single-block-open.slim, assets/targets/components/accordion/_accordion.scss, assets/targets/components/base/_typography.scss
=> Fix various problems with style and alignment

assets/targets/components/events/03-multi-date-event-page.slim, assets/targets/components/events/04-single-date-event-page-with-presenters.slim, assets/targets/components/events/05-single-date-event-page-mixed-markup.slim
From h2 below the image to h1 above.
=> Update title level and location

assets/targets/components/tables/02a-sortable-table.md, assets/targets/components/tables/sortable.js
=> Add filter during setup to allow reversal of initial ordering

assets/targets/injection/header/index.es6, assets/targets/injection/nav/index.es6
=> Make placeholder and ARIA label consistent in injected search forms

assets/targets/components/media/_images.scss, assets/targets/components/people/03-staff-listing-detailed.slim, assets/targets/components/people/04-staff-listing-detailed-diamond.slim
Added some documentation examples too.
Close #332 - added the proposed style as `.semi-desaturate` (70%), and defined `.desaturate` as 100% grayscale.
=> Add image desaturate classes

assets/targets/components/text/03-01-notes.md, assets/targets/components/text/03-02-blockquote.slim, assets/targets/components/text/_blockquote.scss, assets/targets/components/text/_figures_floating.scss
* Migrate modern style subclass back to semantic blockquote
* Refactor modern blockquote style into legacy markup ✨
=> Fix default blockquote styles

assets/targets/components/base/_layout.scss, assets/targets/components/tabs/02-sidebar-tabs.slim, views/templates/course.slim, views/templates/fake-tab.slim, views/templates/no-header.slim, views/templates/search.slim, views/templates/staff-news.slim
Add inner wrapper for wide viewport & update example layouts
=> Minor tweak to sidebar layouts to maintain proportion on resize

assets/targets/injection/nav/localnav.es6
=> Allow for faulty markup in local nav

assets/targets/components/text/_blockquote.scss, views/pages/designers-start.slim.md
Also update content example
Fixes #739
=> Set max-width on new style blockquote

assets/targets/components/base/03-07-ordered-list-bracket.slim, assets/targets/components/base/_typography.scss
Set a fixed width in label space and align to right. This will allow 3 digits in the counter label, will reassess when/if this isn't enough 😄 
Fixes #742
=> Fix bracket list label alignment

Gemfile, Gemfile.lock, assets/server.js, assets/targets/components/base/03-07-ordered-list-bracket.slim, assets/targets/components/base/_typography.scss, assets/targets/components/text/_blockquote.scss, assets/webpack.config.js, config.ru, npm-shrinkwrap.json, package.json, views/pages/designers-start.slim.md
Also adjust webpack-dev-server, babel config.
This only affects the local dev environment, no design system changes
=> Upgrade to node 6.5.0

assets/targets/components/notices/00-overview.md, assets/targets/components/notices/01-examples.slim, assets/targets/components/notices/02-flash-messages.slim, assets/targets/components/notices/_notices.scss, assets/targets/components/notices/_shared.scss
=> Rework inner style and markup for alerts

assets/targets/components/base/_courses.scss, views/templates/course.slim
=> Match style for h1 and h2 on course title template

assets/targets/components/buttons/_buttons.scss
=> Fix long standing button stacking problem

assets/shared/_normalize.scss, assets/targets/components/buttons/_buttons.scss, assets/targets/components/forms/_forms.scss, assets/targets/components/gallery/_photoswipe.scss, assets/targets/components/media/_images.scss, npm-shrinkwrap.json, package.json
- https://github.com/necolas/normalize.css/blob/master/normalize.css
- remove obsolete normalisation styles
- make buttons consistent across browsers, but also across implementations (`button`, `input`, `a`).
=> Add normalize.css

assets/targets/components/news/04-news-single.slim, assets/targets/components/news/_article.scss
=> Add style adjustments for blockquote in article container

assets/targets/components/accordion/index.js
Fix #533
Please merge PR #799 before this one.
=> Restore scrolling position in single-block-open accordion

assets/targets/injection/nav/_localnav.scss, assets/targets/injection/nav/localnav.es6
- `button-ui` specificity
- `no-js` class
=> Fix localnav regressions in v5 and below

README.md
Also, give the README a bit of a clean-up.
=> Document process to update the legacy injection

assets/targets/components/events/_events-detail.scss
=> Fix line-height regression in event details component

assets/shared/_vars.scss
..to pass contrast check on non-white bg
As requested by Andrew N
=> Minor adjustment to lighterblue var

assets/targets/injection/nav/_globalnav.scss, assets/targets/injection/nav/index.es6
Also recreate h2 styles in new class.
As requested by Andrew N
=> Refactor h2 into a classed non-hierarchy block

assets/components/listings/_simple-listing.scss
=> Fix simple listing when used inside section

assets/components/announcement/index.es6, assets/components/tabs/_tabs.css, assets/components/tabs/index.css, assets/components/tabs/index.js, assets/targets/uom/index.es6, assets/utils/index.es6, package.json, yarn.lock
- expose `hashString` and `debounce` utility functions
- upgrade dotenv and perfect-scrollbar
- actually load the `localeCompare` polyfill
- fix minor bugs and typos
=> Upgrade dependencies, fix misc. issues and expose more utility functions

assets/components/text/_lead.css
=> Fix lead spacing when jumpnav is active

assets/components/forms/11-01-notes.md, assets/components/forms/11-unstyled-controls.slim, assets/components/forms/12-disabled-fields.slim, assets/components/forms/_forms.css
=> Style disabled text fields and text areas

assets/components/listings/_simple-listing.css
- Make 3-col and 2-col text listings wider.
- Increase font size of all simple listings.
=> Tweak simple listings

README.md, assets/components/accordion/02-single-block-open.slim, assets/components/base/03-05-ordered-list-steps.slim, assets/components/base/04-03-ticked-list.slim, assets/components/events/01-event-listing.slim, assets/components/events/03-event-listing-with-ribbon.slim, assets/components/events/04-multi-date-event-page.slim, assets/components/events/05-single-date-event-page-mixed-markup.slim, assets/components/events/06-single-date-event-page-with-presenters.slim, assets/components/events/_events-detail.css, assets/components/events/_events.css, assets/components/figure/04-other-content-types.slim, assets/components/news/06-news-single-with-video.slim, assets/components/tables/sortable.js, assets/shared/component-manager.es6, roda-render_component.rb, views/templates/course.slim, views/templates/floating-contrast.slim, views/templates/homepage.slim
Lots of last minute fixes. See commits for more info.
=> Misc. fixes

assets/components/events/_events-detail.css, assets/components/events/_events.css, assets/components/news/_article.css
=> Fix bugs with figures and embeds when used inside events

assets/components/people/05-profile-header.slim, views/templates/people-profile-page.slim
Update Chaz’s mobile number on the template examples so he stops getting spammed by marketers.
https://web.unimelb.edu.au/layouts/people-profile-page/
https://web.unimelb.edu.au/components/people/
=> Remove chaz phone

assets/components/footer/index.es6, assets/components/nav/index.es6
=> Update nav links
