assets/targets/components/base/_layout.scss
Cancel out the `display: table` declaration for nested divs.
Chaz confirmed this solves the issues he reported.
=> Fix nested divs in aside layout

assets/targets/components/gallery/01-default-gallery.slim, assets/targets/components/index.js, assets/targets/debranded/index.js
Issue #344
Use a closure inside an IIFE to isolate the `g` variable that holds the
galleries’ root DOM elements.
=> Fix ImageGallery initialisation code

assets/targets/components/listings/_nav_block.scss
Use margin auto on child elements and increase items’ width slightly from 32 to to 32.5%, but cannot increase to the optimal 33.33% due to spaces of unknown width between
inline-block items.
=> Improve nav-block centring

assets/targets/components/tabs/_tabs.scss
As it turns out, the inner tab `div div` was used to control visibility of side tabs on a very specific inner page of bespoke (degree structure). Fixing it here to keep the styles canonical.
=> Override display styles for course page side tabs

assets/targets/components/tabs/_tabs.scss
To hide visible scrollbars in already styled degree structure layout
Fixes #384
=> Override mobile wrap overflow

assets/targets/components/forms/_forms-select.scss, assets/targets/components/forms/fancyselect.js, assets/targets/components/index.js, assets/targets/debranded/index.js, assets/targets/forms/index.js, doc-site/views/example_layouts/intranet.slim
… with class `select--nav`.
FancySelects had to be enabled on IE8/9, which required some targeted styling tweaks. Notably, the selects were misbehaving (http://stackoverflow.com/questions/5551288/ies-select-boxes-closes-themselves-when-hovering), which turned out to be caused by changing the `background-color` on hover. Colours are now set for each select design.
=> Turn FancySelects into navigation menus

assets/targets/components/headers/_headers.scss, assets/targets/components/inpage-navigation/_jumpnav.scss, doc-site/pages/getting-started.slim.md, doc-site/views/components_index.slim
Adds separate semantic element for headerless border-top - this was initially a convenience for CMS (role="main" is in the layout and can't easily have classes added and removed).
Also noticed that the current implementation (on role="main") doesn't work well with the in page navigation anyway, so this solution might be a little more robust. The previous implementation is still here as well.
=> Alternate syntax for headerless

assets/targets/components/maps/lmaps.js
Point to OpenStreetMap’s copyright page rather than homepage. Fixes #387.
=> Fix OpenStreetMap attribution link

assets/shared/shims.js, assets/targets/components/accordion/index.js, assets/targets/components/tabs/index.js
Add a new helper to find the first element child of a node.
The tabs fix assumes that the only possible child element of a tab is an icon - it assumes that no-one uses spans, strong, etc. for other purposes.
=> Fix white space issues in accordion and tabs

assets/targets/components/news/04-news-single.slim, assets/targets/components/news/_article.scss
Fixes #427. Allow the use of figures with class `full-width` inside news articles.
=> Fix figure inside news article

assets/targets/components/events/04-single-date-event-page-with-presenters.slim, assets/targets/components/events/_events-detail.scss, assets/targets/components/icons/_svg.scss
- `social` class already used in injected footer, so use `social-links` instead.
- Scoped to Event pages (`.details`) until further notice.
- Also add a class for visually hiding an icon's label: `icon--hide-label`.
=> Social links to share events

assets/targets/components/inpage-navigation/_jumpnav.scss, assets/targets/components/news/_article.scss, assets/targets/components/news/_list.scss, assets/targets/components/search/02-search-results.slim, assets/targets/components/search/_search-results.scss, assets/targets/components/text/_figures_floating.scss
Also, fix the map icon in the search results template.
In the news listing, I've set to top and bottom margin of the floated image to `-1rem`. Thought the listing had too much space inside it otherwise. Not sure if what I did is better, though... Feel free to revert the margin to 0.
=> Clearfix search and news listings

assets/targets/components/tabs/_tabs.scss, assets/targets/components/text/_lead.scss
- fix top/bottom padding [removed in
v3.4.1](https://github.com/marcom-unimelb/unimelb-design-system/commit/7
8cfd5aab572c2a44c3f3b31fa726a6ae9c1837d)
- use padding rather than margin for 3% left/right spacing (thus remove the need to worry about switching to auto left/right margin at various breakpoints)
- add [role="main"] to override section styles
- account for jump-nav bottom padding on mobile to get the same spacing
above and below the lead text
- generalise removal of top padding on sections that follow leads
=> Fix lead text padding

assets/targets/components/index.scss, assets/targets/debranded/index.scss
Use system default fonts while webfontloader loads or times out, font stack taken from https://medium.com/@mwichary/system-shock-6b1dc6d6596f
=> Force FOUC on webfontloader inactive and loading states

assets/targets/components/listings/10-navigational-block-listing-with-linked-header.slim, assets/targets/components/listings/_nav_block.scss
Might need to back-date this to v3.5 and redeploy on the same code (it's only a few small css changes)
=> Duplicate missing styled heading from text-listing to block-listing

assets/targets/injection/nav/index.js
On sites powered by Turbolinks like Pursuit, an unexpected state
object was passed to the `update` method when navigating back in
history (`{ turbolinks: true, url: '...' }` instead of `{ local: false,
global: false }`).
=> Fix nav history bug on sites powered by Turbolinks

assets/shared/_patterns_accessibility.scss, assets/targets/components/forms/10-inline-form.slim, assets/targets/components/icons/_svg.scss
When used inside button, the label of an icon with a hidden label
creates a weird outline.
=> Fix icon with hidden label

assets/targets/components/forms/index.js
Use `stopImmediatePropagation` to prevent other `submit` listeners from being called. Also, smooth scroll to top of form on validation error.
=> Fix form submit propagation

assets/targets/components/gallery/00-overview.md, assets/targets/components/gallery/index.js, assets/targets/components/index.js, assets/targets/debranded/index.js
Move loading of `photoswipe.js` with `loadScript` outside of the `ImageGallery` class to ensure it is never loaded more than once (i.e. when multiple galleries are used on the same page).
=> Fix Photoswipe library loaded more than once

assets/targets/components/icons/_svg.scss
Since SVG icons do not work on IE8, labels must always be shown.
=> Fix icons with hidden label on IE8

assets/targets/injection/header/index.es6
(i.e. don't wait for first scroll)
=> On page load, check right away whether header should have class `fixed`

assets/targets/components/tabs/index.js
Fixes #523
1. Refactor panel selection algorithm, especially to make sure that:
- in-page tabs cannot be selected via the URL hash, and
- a navigational tab that contains an in-page tab that matches the URL hash doesn't get selected (this feature is for inner/sidebar tabs only).
2. Don't set the page's location when selecting an in-page tab (this feature is for navigational tabs only).
=> Fix in-page tabs

assets/targets/components/index.js, assets/targets/components/maps/04-pin.slim, assets/targets/components/maps/04-pins.slim, assets/targets/components/maps/07-openstreetmap.slim, assets/targets/components/maps/gmaps.js, assets/targets/components/maps/lmaps.js
Fixes #524 
The `data-pin` attribute now accepts pairs of coordinates separated by pipes (`|`) - e.g. `data-pin="-37.798535, 144.960605|-37.798048, 144.960946"`
Also, fix mixed content issue on `https://web.unimelb.edu.au` by loading `leaflet.css` from `cdnjs`, which supports HTTPS.
=> Allow adding multiple pins to a gmap

assets/targets/components/inpage-navigation/_jumpnav.scss
Fixes #502. This will work only in browsers that support both the `@supports` directive and the `column-span` property. At the moment, this includes Edge and Chrome, but excludes Firefox and IE<11.
Also, add a slight margin below the jumpnav heading on mobile.
=> Use CSS column layout for jumpnav on mobile, if supported

assets/shared/smoothscroll.js, assets/targets/components/inpage-navigation/00-overview.md
In Pursuit, this means that the preloading of the next article can start after the smooth scroll rather than at the same time (which results in a jagged scrolling animation).
=> Let the smooth scroll function accept a callback

assets/shared/_globals.scss, assets/shared/blanket.scss, assets/targets/components/_print.scss, assets/targets/injection/index.scss, assets/targets/injection/nav/_globalnav.scss, assets/targets/injection/nav/_localnav.scss, assets/targets/injection/nav/_modal.scss, assets/targets/injection/nav/_nav.scss, assets/targets/injection/nav/index.js, assets/targets/injection/nav/index.scss, assets/targets/injection/nav/localnav.es6, assets/targets/injection/patterns.scss
Fixes #438. Let local and global nav fly over the page rather than push it. Reasons and benefits:
1. Brings much better performance and looks better visually, as the page's header and inner elements were always slightly out of sync during the animations.
2. Fixes #440: the page no longer jumps back to the top when the nav is opened. This was a significant issue in Pursuit.
3. The (dis)appearance of the page's scrollbar was causing a slight jag. Now, when the nav is opened, the scrollbar remains visible and the page scrollable.
Additional improvements and fixes:
- remove transform and transition mixins; let autoprefixer do its job
- declare styles like `transition` and `z-index` in the normal state of an element instead of in its active state
- similarly, ensure that a `transform` …
=> Refactor menu animation

assets/targets/components/search/_search-results.scss, doc-site/views/example_layouts/search.slim
Add margin override to force left align when missing contact detail content (needed on full search template, where `display:table` inherits from an outer `display:table`)
Doesn't seem to occur in webkit.
=> Fix centre-aligned edge case FF search result

assets/targets/components/headers/_blurred.scss
Increase spread to cover hard boundary on safari and FF
Fixes #542
=> Smooth out blurred header boundary

assets/targets/injection/header/index.scss
* Revert to `position: relative` to allow z-index stacking
=> Fix missing shadow under header at mobile width

assets/targets/components/tabs/_tabs.scss
There was a very slight colour difference on a particular page due to legacy styles that were incorrectly left there after the university-general colour scheme was added.
=> Revert to transparent on inner unit

assets/targets/components/tabs/index.js
The default anchor click handler is sometimes called when clicking on in-page tabs. This leads to unwanted smooth scrolling. Stop immediate propagation of click event so that the default handler is never called.
=> Fix propagation of click event on inpage tabs

.github/ISSUE_TEMPLATE.md, assets/targets/components/buttons/_buttons.scss, assets/targets/components/tabs/_tabs.scss, assets/targets/components/tabs/index.js, assets/targets/components/tabs/index.scss
- show horizontal scrollbar when it receives focus
- fix/remove moz-inner-focus and add proper focus outline to arrows
- append left arrow before tabs to match visual order
- work around cropped focus outline on tabs (because of `overflow: hidden` on parent)
- fix regressions introduced by #551 :
- smooth scroll to tab bar on click (but only for navigational tabs)
- follow external links
- fix smooth scroll to tab bar when clicking a tab in Firefox - fixes #554 
- more generally, refactor click handling code to remove all side effects
=> Tabs: improve accessibility and fix misc. bugs

assets/targets/components/tabs/_tabs.scss
Fixes #552
Safari behaves like `transparent` is actually `rgba($black, 0)`...
=> Fix gradient background on tabs arrows

assets/targets/components/accordion/02-single-block-open.slim, assets/targets/components/accordion/_accordion.scss
Ideally, we want to get away from using the `ul > li` relationship for accordions altogether, but that will be a refactor for another day.
Fix #556
=> Fix loose inheritance on accordion container

assets/targets/components/index.js, assets/targets/components/maps/gmaps.js, assets/targets/components/maps/lmaps.js
I ran into a number of reload problems with external libraries (gmaps & leaflet) not playing well with the live reloading editor I'm using in the next gen docs app - this fix should help with turbo links as well.
=> Fix reload problems on both mapping solutions

assets/targets/components/modal/00-overview.md, assets/targets/components/modal/02-offset-positioning.slim, assets/targets/components/modal/_modal.scss, assets/targets/components/modal/index.js, assets/targets/injection/nav/_modal.scss, assets/targets/injection/nav/_nav.scss
Fixes #571
- never position the modal above viewport top (40px minimum)
- update the documentation slightly
- document the `data-modal-offset` attribute and demonstrate its use in the second example
=> Fix modal position

assets/targets/injection/icons/_svg.scss
Breadcrumb home icon gets duplicated when combining v4.0 injection + v3.5.2 (and below) components. This workaround consists of simply hiding the second icon... I think the only way to fix this will be to move the entire rebind logic to the injection and refactor it so that the components register themselves as being rebindable.
=> Workaround for breadcrumbs icon bug

assets/targets/injection/icons/_svg.scss, assets/targets/injection/icons/iconhelper.js, assets/targets/injection/index.js
Check that UOMbind exists before executing UOMbindIcons.
In v4.0, the IconHelper class was moved to the injection. As a result, in versions prior to 4.0, the helper gets called twice for each icon. This is fine as long as the helper checks the `data-bound` attribute to ensure the same icon doesn't get initialised twice. Unfortunately, this attribute was added only in v3.6 with `UOMbind`; hence the need to check that `UOMbind` exists. Without it, icons would get initialised twice in v3.5.2 and below.
=> Fix icon helper bug

assets/targets/components/pathfinder/_pathfinder.scss
It was overridden by the `-2` version.
Fixes #610
=> Reinstate missing border gap

assets/targets/components/events/_events-detail.scss
Set overflow on long nonwrapping text, remove unnecessary left padding
Fixes #559
=> Minor style fixes to event detail

assets/targets/components/tabs/index.js
Create and fire a `resize` event to activate any 3rd party code listening for that event (gmaps, isotope).
At the moment this is only run in the tabs, might be useful in other areas too.
Fixes #208
=> Trigger listening 3rd party code

assets/targets/components/news/_list.scss
Cancel out the max-width from `section div`, which gets applied when
the news index is wrapped inside a section.
=> Fix max-width of news index when wrapped inside a section

assets/targets/components/media/05-youtube.slim, assets/targets/components/media/_videos.scss, assets/targets/components/media/index.scss
Also:
* Remove 4:3 (deprecated on youtube)
* Move main styling setup into placeholder to avoid over-duplication of compiled styles
Fixes #620
=> Add 21:9 aspect for video embeds

assets/shared/_globals.scss, assets/shared/_patterns_normalize.scss, assets/targets/components/_print.scss, assets/targets/components/base/_titles.scss, assets/targets/components/base/_typography.scss, assets/targets/components/listings/_block.scss, assets/targets/components/pathfinder/_pathfinder.scss, assets/targets/injection/header/index.scss, assets/targets/injection/patterns.scss
Let autoprefixer decide which ones to add at build time.
- Prefixes for non-standard properties (e.g. column break, font smoothing) and pseudo-selectors (e.g. placeholder) have not been touched.
- Old gradient declarations have been removed except for the IE9 `filter` fallback.
- The implementation of the `hue-rotation` animation on `h1.highlight` has been simplified: the background doesn't need to be clipped to the text because the `hue-rotate` filter works on the text itself.
=> Remove vendor prefixes

assets/targets/components/tabs/index.js
Add hard jump to tab position for FF and IE to prevent random footer-scroll on tabbed page
Fixes #528
=> Fix unexpected scroll in FF

assets/targets/components/events/05-single-date-event-page-mixed-markup.slim
Broken link had been reported. Given it's just example text, I've removed the link entirely.
=> Removed link in example text that no longer works

assets/targets/components/base/04-02-complex-lists.slim, assets/targets/components/base/_typography.scss
Also:
* expand documentation
Note- the style is only resettable to 3 levels ie.
```
<ul type="d">
<li>
<ul type="a">
<li>
<ul type="i">
```
`1. a) i.`
(The above combination of nested list-type is set by default for all `ol`, so you won't need to add `type` if this style is suitable) 
Fix #641
=> Add typed ol

assets/targets/components/index.js, assets/targets/components/inpage-navigation/index.js, assets/targets/components/tabs/01-full-width-navigation-tabs.slim, assets/targets/components/tabs/_tabs.scss, assets/targets/components/tabs/index.js, package.json
Queryselector can only match an ID that starts with a number *if the string is escaped*.
eg. using `<h2 id="2012">Photos from 2012</h2>` as an anchor to the jump nav will cause a DOM Exception 12, originating from the queryselector call.
This PR introduces an external dependency, `cssesc`, to escape the ID string.
Ref: https://mathiasbynens.be/notes/css-escapes
=> Escape numeric id for smooth scroll

assets/targets/components/events/01-event-listing.slim, assets/targets/components/events/02-event-listing-with-presenters.slim
This PR provides an example multi-date event (e.g. exhibitions) example that seems to make sense. I can't think of any other way to display this sort of info in a chronological way.
=> Update event example to accomodate multi-day events

assets/targets/components/listings/_block.scss
Also: the block needs to have 100% height within its container. This doesn't seem to affect other browsers.
Fixes #649
=> Use fixed height to mitigate IE flexbox implementation

assets/targets/injection/header/index.es6
We've been using `name="query"` for a long time, at least since the v2/3 rewrite, the GSA needs `name="q"`.
=> Change search form name attr to q

assets/targets/components/base/03-03-ordered-list-uppercase-alpha.slim, assets/targets/components/base/03-04-ordered-list-uppercase-roman-numerals.slim, assets/targets/components/base/04-02-complex-lists.slim, assets/targets/components/base/_typography.scss
HTML ​is​ case sensitive, so `type="A"` is different to `type="a"`. But CSS is ​_not_​ case sensitive, so it can't differentiate those two selectors (the last declaration in source order overrides the first). 
There was an odd hack that allowed both upper- and lower- alpha, but it didn't work for roman so I'm going to leave the system with lower only for consistency. Note: this would all be fixed by *never* changing default `list-style-type` on bare/unclassed elements, ie. use BEM. Doc examples removed to avoid confusion.
=> Fix lower/upper default ol types

assets/targets/components/base/05-colour-palette-no-source.slim
[Colour palette](http://web.unimelb.edu.au/components/base/#colour-palette) had the same blue twice and with the wrong hex value.
=> Fix colour palette

assets/targets/injection/index.js, views/pages/getting-started.slim.md
Replace `no-js` class with `js` on `html` element when the page loads. Also, use `no-js` class in markup example on [Getting started](https://web.unimelb.edu.au/getting-started/) page.
=> Fix toggling of JS classes on document root

assets/targets/components/notices/02-flash-messages.slim, assets/targets/components/notices/flash.js
Fixes #714. Markup must be placed after `header` or `.headerless` element.
=> Improve flash messages documentation

assets/shared/smoothscroll.js, assets/targets/components/inpage-navigation/jumpnav.js, assets/targets/injection/header/index.es6
Firefox sniffing was previously required when scrolling the page programmatically or retriving the page's scroll position (via `[documentElement|body].scrollTop`). Now that IE8 support is not required, we can use `window.scrollTo()` and `window.[scrollY|pageYOffset]`.
This PR improves a couple of other things; see first two commits for more info. I've also ignored one instance of Firefox sniffing, as it has already been removed in #607.
=> Remove Firefox sniffing

assets/targets/components/gallery/_gallery.scss, assets/webpack.config.js, package.json
Autoprefixer stopped prefixing CSS transforms with `-ms` because IE9 must have dropped below 1% global market share.
This PR restores support for IE9 by overriding the default autoprefixer configuration. It also replaces `autoprefixer-loader` with `postcss-loader` and `autoprefixer`, as the former is deprecated.
=> Fix broken nav on IE9

assets/targets/components/_print.scss, assets/targets/components/base/02-typography-guidelines-no-source.slim, assets/targets/components/base/_courses.scss, assets/targets/components/base/_layout.scss, assets/targets/components/base/_timetable.scss, assets/targets/components/events/03-multi-date-event-page.slim, assets/targets/components/events/04-single-date-event-page-with-presenters.slim, assets/targets/components/events/05-single-date-event-page-mixed-markup.slim, assets/targets/components/events/_events-detail.scss, assets/targets/components/filtered-listings/04-listing.slim, assets/targets/components/filtered-listings/_listing.scss, assets/targets/components/news/04-news-single.slim, assets/targets/components/news/05-news-single-with-image.slim, assets/targets/components/news/06-news-single-with-video.slim, assets/targets/components/news/_article.scss, assets/targets/components/tabs/02-sidebar-tabs.slim, assets/targets/components/tabs/_tabs.scss, views/templates/course.slim, views/templates/event.slim, views/templates/fake-tab.slim, views/templates/index.slim, views/templates/no-header.slim, views/templates/search.slim, views/templates/staff-news.slim
We've found that the content in `<aside>` on production design system sites is typically a heading, and some contextual description, this does not follow the intended use [(tangential content)](http://www.w3.org/TR/html-markup/aside.html) of this element.
To avoid any risk of assistive technologies skipping the content of a semantic `<aside>`, this PR replaces all styling and documentation mentions with `<div class="aside">` instead. 
This is a breaking change!
=> Rename semantic aside element to div class=aside

assets/targets/components/forms/01-notes-no-source.md, assets/targets/components/forms/01-text-field.slim, assets/targets/components/forms/_forms.scss
Remove defined placeholder colour altogether (use browser default), add note about using labels.
Fixes #699
=> Use consistent colour between input and textarea placeholders

assets/targets/components/forms/11-01-notes.md, assets/targets/components/forms/11-02-unstyled-controls.slim, assets/targets/components/forms/_forms.scss
Refactor CSS to allow `radio` and `checkbox` controls to be unstyled for custom CMS usage, removed up old IE browser sniffing (media query).
Fixes #719 
Fixes #470
=> Unsettled radio/checkbox controls

assets/targets/components/base/_typography.scss
Base level `ul` and `ol` had the padding shifted during development of alternate styles - this has been restored to the correct amount now (no padding above, padding below).
Fixes #703
=> Fix base level list padding

assets/targets/components/tabs/02-sidebar-tabs.slim, assets/targets/components/tabs/sidebar-tabs.js
* Add `data-scroll-target` and `data-no-scroll` hooks
* Update documentation
=> Fix default scrolling behaviour for sidebar tabs

assets/targets/components/modal/_modal.scss
Including an iframe inside a modal (not advised anyway) can sometimes cause the iframe content to peek above page content at pageload: this PR will hide it with CSS.
Interestingly, this was caused by the bug "fix" for IE8 in v3.1 that moved the modal DOM relocation to the click event. Before then, the modals were outside the page container and couldn't peek above.
=> Hide 3rd party embeds at page load

assets/targets/components/tabs/02-sidebar-tabs.slim, views/templates/course.slim, views/templates/fake-tab.slim, views/templates/no-header.slim, views/templates/search.slim, views/templates/staff-news.slim
The `box` helper removes the top/bottom spacing from the first/last _direct_ children only, so it has to go on `.layout-sidebar__main__inner` and `.layout-sidebar__side__inner`.
=> Fix use of `box` helper class with sidebar layout

assets/shared/_normalize.scss
Fix #750 by setting `min-height` rather than `height` to 100% on body.
https://codepen.io/absolutholz/post/html-and-body-element-height-100
=> Fix Firefox printing issue

assets/targets/components/base/_layout.scss, assets/targets/injection/nav/_localnav.scss, assets/targets/injection/nav/localnav.es6, views/_nav.slim, views/pages/getting-started.slim.md
Use global `no-js` class instead. Also, remove an unused `.no-js` selector (see commit for explanation).
The [recommended markup](https://web.unimelb.edu.au/getting-started#local-nav) for the local nav has changed: the root element with `id=sitemap` no longer needs the `no-js` class.
=> Remove `no-js` class from localnav

assets/shared/_normalize.scss
This ensures that elements are hidden even if they have a custom `display` property. Note that normalize.css doesn't set `!important` for `[hidden]`, which is why it's back in our own normalisation partial.
This should not break anything, but may uncover bugs where the `hidden` class or attribute was being set by mistake. Any overrides meant to work around this issue can now be removed, for instance:
```
/* REMOVE */
.element.hidden { display: none !important; }
/* REPLACE */
.element:not(hidden) { display: block; } /* BEFORE */
.element { display: block; } /* AFTER */
=> Force elements with `hidden` class or attribute to be hidden

assets/targets/components/maps/_maps.scss
Fix #642
Gmaps always have a fixed width (400px by default), so the max-width can be 100% instead of 600px without compromising the design. This allows the maps do never overflow on mobile.
=> Fix max-width of Gmaps on small viewports

assets/targets/components/_print.scss, assets/targets/components/index.js, assets/targets/components/tabs/_tabs.scss, assets/targets/components/tabs/index.js, assets/targets/debranded/index.js, views/templates/course.slim, views/templates/fake-tab.slim
Fix #717 
This deprecates the `tabbed-course` class, which was just an alias for `tabbed-nav`. If your site uses the `tabbed-course` class to implement full-width tabs, simply replace it with `tabbed-nav`.
=> Deprecate tabbed-course

assets/targets/injection/header/index.es6
Use `nav` element for `page-header-navigation` and `page-header-tools`, and label breadcrumbs.
- Fix #786 
- Fix #787
=> Improve accessibility of injection

assets/targets/components/gallery/01-default-gallery.slim, assets/targets/components/gallery/02-captions.slim, assets/targets/components/gallery/02-small-and-medium.slim, assets/targets/components/gallery/03-captions.slim, assets/targets/components/gallery/_gallery.scss, assets/targets/components/gallery/index.js, assets/targets/components/gallery/index.scss, assets/targets/components/index.js, assets/targets/debranded/index.js, npm-shrinkwrap.json, package.json
Big revamp of the gallery component: code clean-up, performance improvements, bug fixes and new features.
- Fix #671 - allow showing an image's caption in the gallery listing with class `image-gallery__caption`. The class can be added to:
- the `figcaption` element in order to show the same caption in the gallery as in the viewer,
- a separate paragraph element in order to show a different, shorter caption in the gallery.
- Fix #733 - add variant classes for small and medium-width galleries: `image-gallery--small` and `image-gallery--medium`.
- Fix zoom icon on hover, and change cursor to `zoom-in`
- Centre captions in viewer
- Fix animation on open/close:
- improve performance by not triggering a reflow, and
- fix jankyness by fixing thumbnail bounds computation and enabling opacity …
=> Gallery revamp

assets/targets/components/listings/17-logo-listing.slim, assets/targets/components/listings/_logo.scss, assets/targets/components/listings/index.scss
Create new listing for vertically aligned display of logos, as per doc example:
- Fix #801 
- Fix #698
=> Add logo listing

assets/targets/components/base/_layout.scss, assets/targets/components/buttons/_buttons.scss, assets/targets/components/events/_events-detail.scss, assets/targets/components/events/_events.scss, assets/targets/components/forms/_forms-select.scss, assets/targets/components/people/_profile-header.scss, assets/targets/components/search/_search-results.scss, assets/targets/components/tabs/index.js, assets/targets/injection/header/index.scss, assets/targets/injection/icons/_svg.scss, assets/targets/injection/icons/iconhelper.js
Don't inject `.icon-over` when binding icons, and prevent icons from beeing focusable in IE with `focusable="false"` (fix #669).
This shouldn't break anything. Any overrides targetting `icon-over` can safely be removed.
=> Remove icon-over hack

assets/targets/components/accordion/_accordion.scss, assets/targets/components/accordion/index.js, assets/targets/components/base/_courses.scss
- Fix #486 - distinguish sub-headings in `course-progression` table
- Improve design of selectable rows in `course-progression` table: increase font size, remove default underline, show underline on hover, and bold when selected
- Get rid of the sticky focus outlines by managing focus of all accordions more smartly:
- give focus to panel on open
- blur trigger on close
- => trigger no longer keeps focus after being clicked
- => default focus outline can be restored to help keyboard users
=> Distinguish degree structure headings and improve accordion accessibility

assets/shared/_normalize.scss
Override `bolder` for `b and `strong` introduced by `normalize.css`. The design system's default font-weight is 300 for Roboto, and Roboto's 400 weight is not bold enough.
=> Fix bold regression

assets/shared/_vars.scss, assets/targets/components/search/02-search-results.slim, assets/targets/components/search/_search-results.scss
Allow adding a definition list below a search result's heading to display meta information, like the year and type for a handbook search result.
=> Meta info for search results

assets/shared/_normalize.scss, assets/targets/components/buttons/_buttons.scss, assets/targets/components/modal/_modal.scss, assets/targets/components/tabs/_tabs.scss, assets/targets/injection/nav/_localnav.scss, assets/targets/injection/nav/_modal.scss, assets/targets/injection/nav/index.es6, assets/targets/injection/nav/localnav.es6, views/_nav.slim, views/pages/getting-started.slim.md
Fixes #773 - `inner` wrappers can now be omitted in the [local nav markup](http://web.unimelb.edu.au/getting-started/#local-nav), in which case they are injected automatically. Note that this does have a very small impact on performance, so if you're able to provide the wrappers yourself, please do so.
This PR also includes a complete refactoring of the `LocalNav` component. Below is a non-exhaustive list of the changes:
- use `button` rather than `span` for close/back buttons
- add BEM classes on the fly in order to clean-up the CSS and reduce the number of overridden styles
- make nested panels look the same as the root panel
- underline links on hover
- move event bindings for local nav elements out of the `InjectedNav` component and into the `LocalNav` component (pass  required …
=> Refactor local nav and make `inner` wrappers optional

assets/targets/injection/tealium/index.js
Looks for the `uom.js` script, parses the version number from the `src` and pass it to Tealium via `utag_data`.
This will allow us to see which versions are no longer used, and which sites are still using old versions and need to be updated.
=> Track design system version

assets/targets/components/block-listing/00-overview.md, assets/targets/components/block-listing/01-block-listing.slim, assets/targets/components/listings/_block.scss
- remove legacy `top-unit` containers from markup
- fix `crop-height` container
- implement new background-image option
- round rem values in output (e.g. 16px instead of 15)
- fix spacing of various elements, espcially in event/exhibition tiles
- fix centring of listing on page (0.5% margin on either side of every tile instead of 1% on the right)
- fix fading at bottom of news tiles
- document `crop-height` and `no-anim` and improve example markup
=> Fix various block listing issues

assets/shared/_normalize.scss
Abbreviations had solid underline in Chrome: https://github.com/necolas/normalize.css/pull/468#issuecomment-174107494
=> Fix regression of abbreviation style introduced by normalize.css

assets/targets/components/base/_typography.scss, assets/targets/components/notices/_notices.scss
- use `wrapper` mixin for notices to get the same behaviour as paragraphs on mobile (94% width)
- force `margin-left: 0;` and `max-width` on direct children of steps list to bypass selector specificity issues
=> Fix responsive styles of notices and children of steps list

assets/targets/injection/tealium/index.js
Some WordPress sites append a query string at the end of the `uom.js` script URL.
=> Relax version tracking regex

assets/targets/components/gallery/01-gallery.slim, assets/targets/components/gallery/index.js
... rather than from thumbnails dimensions, as thumbnails may not have fully loaded when gallery code runs.
=> Compute gallery image ratios from `data-size` attributes

assets/targets/components/tabs/index.js
Fix #842
The tab panels were being initialised in the wrong order, so when attempting to switch to a tab at a specific index, the wrong panel was being shown (e.g. when trying to switch to tab no. 1 in a 3-tab component, it would switch to tab no. 3).
=> Fix tab panels initialisation order

assets/components/enquiry/01-enquiry.slim, assets/components/enquiry/02-enquiry-dark.slim, assets/components/footer/index.es6, views/pages/audio-video-guidelines.slim.md, views/templates/fake-tab.slim, views/templates/intranet.slim
Fix #851 
The links in the terms and conditions of the enquiry component have been updated. One of the links was broken and the other was pointing to the _Disclaimer_ rather than _Privacy_ page.
=> Update links in footer and enquiry component

package.json, yarn.lock
[`babel-preset-env`](https://github.com/babel/babel-preset-env/blob/master/README.md) performs only the transforms required for the target environment (i.e. the list of supported browsers), as opposed to the previous preset `babel-preset-2015` which was performing all ES2015 transforms no matter what.
Basically, if one day all supported browsers support some new JS syntax, then that syntax won't be transformed to ES2015. This is not very useful right now since we still support IE9, but it will be when the list of supported browsers changes in the future. Moreover, Babel is about to deprecate `babel-preset-2015` in favour of `babel-preset-env`.
=> Switch to babel-preset-env

assets/components/accordion/index.js, assets/components/checklist/checkboxhelper.js, assets/components/checklist/index.js, assets/components/forms/fancyselect.js, assets/components/forms/index.js, assets/components/icons/index.js, assets/components/inpage-navigation/index.js, assets/components/inpage-navigation/jumpnav.js, assets/components/maps/lmaps.js, assets/components/modal/index.js, assets/components/notices/flash.js, assets/components/tables/index.js, assets/components/tables/sortable.js, assets/components/tabs/index.js, assets/shared/component-manager.es6, assets/shared/create-namespace.js
- remove all occurrences of "use strict" made obsolete by webpack
- always initialise `props` object in component constructors in case one is not passed
=> Cosmetic tweaks

assets/components/search/02-search-results.slim, assets/components/search/_search-results.css, assets/shared/component-manager.es6
Fix #840 - Display a list of sub-links underneath a search result.
=> Sub-links in search results

assets/components/accordion/_accordion.css, assets/components/base/03-05-ordered-list-steps.slim, assets/components/base/_typography.css, assets/shared/_globals.css
Hopefully for the best...
- **Breaking change!** Deprecate using class `ticked-list` on a wrapper of the actual `ul` element.
- Fix and simplify spacing styles, especially with nested lists
- Fix #810 - all first-level lists now have 1.5rem bottom spacing; list items (last child excepted) have .5rem bottom spacing; and nested lists have .5rem top spacing and no bottom spacing.
- Keep only one list mixin, `inner-list-rest`, with much simpler styles, to specifically restore root list spacing to lists that are used inside list-based components (e.g. accordion, steps list).
Before | After
--- | ---
=> Review spacing of lists and list items

assets/components/footer/index.es6, assets/components/header/index.es6, assets/components/icon-set/index.js, assets/components/nav/index.es6, assets/shared/component-manager.es6, assets/shared/create-namespace.js, assets/targets/forms/index.es6, assets/targets/uom/index.es6
Add the following properties and methods to the component manager module, and expose them on the global `window.uom` object:
- `injectionComponents`: the registered injection components by label
- `injectionInstances`: the instances by label (an injection can only ever have one instance) 
- `registerInjectionComponents`: a method to register one or more injection component
- `applyInjection`: a method to initialise all registered injection components
=> Register and expose injection components

assets/components/figure/index.css
Previously, only inset captions were blue.
=> Make all captions slightly blue

assets/components/figure/index.css
Increase specificity of `.figure` selectors to beat `.uomcontent [role="main"] section div`.
=> Fix `div.figure` inside  sections
